<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKLbHM5y\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKLbHM5y/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKLbHM5y.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKLbHM5y\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKLbHM5y\App_KernelDevDebugContainer([
    'container.build_hash' => 'KLbHM5y',
    'container.build_id' => '5c5ddd49',
    'container.build_time' => 1705496133,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKLbHM5y');
